<?php

namespace App\Filament\Resources\Technologies\Schemas;

use App\Containers\AppSection\Portfolio\Data\Repositories\TechnologyRepository;
use App\Filament\Concerns\HasSlugFromName;
use Filament\Forms\Components\TextInput;
use Filament\Schemas\Schema;

class TechnologyForm
{
    use HasSlugFromName;

    public static function configure(Schema $schema): Schema
    {
        return $schema
            ->components([
                self::withAutoGeneratedSlug(
                    TextInput::make('name')
                        ->label('Название')
                        ->required()
                        ->maxLength(255),
                    TechnologyRepository::class
                ),
                self::asReadOnlySlug(
                    TextInput::make('slug')
                        ->label('Слаг')
                        ->required()
                        ->maxLength(255)
                        ->unique(ignoreRecord: true)
                ),
            ]);
    }
}
