<?php

namespace App\Filament\Concerns;

use Filament\Forms\Components\TextInput;
use Filament\Schemas\Components\Utilities\Set;
use Illuminate\Database\Eloquent\Model;
use Illuminate\Support\Str;
use Prettus\Repository\Eloquent\BaseRepository;

trait HasSlugFromName
{
    protected static function withAutoGeneratedSlug(
        TextInput $sourceField,
        string $repositoryClass,
        string $slugField = 'slug',
    ): TextInput
    {
        return $sourceField
            ->live(debounce: 500)
            ->afterStateUpdated(function (Set $set, ?string $state, ?Model $record) use ($repositoryClass, $slugField): void {
                $set($slugField, static::generateUniqueSlug($repositoryClass, $state, $record?->getKey()));
            });
    }

    protected static function asReadOnlySlug(TextInput $field): TextInput
    {
        return $field
            ->readOnly()
            ->dehydrated();
    }

    protected static function generateUniqueSlug(string $repositoryClass, ?string $value, int|string|null $ignoreId = null): string
    {
        $baseSlug = Str::slug($value);

        if ($baseSlug === '') {
            return '';
        }

        $slug = $baseSlug;
        $suffix = 0;

        while (static::slugExists($repositoryClass, $slug, $ignoreId)) {
            $suffix++;
            $slug = "{$baseSlug}-{$suffix}";
        }

        return $slug;
    }

    protected static function slugExists(string $repositoryClass, string $slug, int|string|null $ignoreId = null): bool
    {
        /** @var BaseRepository $repository */
        $repository = app($repositoryClass);

        $where = [
            ['slug', '=', $slug],
        ];

        if ($ignoreId !== null) {
            $where[] = ['id', '<>', $ignoreId];
        }

        return $repository->findWhere($where, ['id'])->isNotEmpty();
    }
}
