<?php

namespace App\Filament\Resources\Projects\Schemas;

use App\Containers\AppSection\Portfolio\Data\Repositories\ProjectRepository;
use App\Filament\Concerns\HasSlugFromName;
use Filament\Forms\Components\Repeater;
use Filament\Forms\Components\Select;
use Filament\Forms\Components\SpatieMediaLibraryFileUpload;
use Filament\Forms\Components\TextInput;
use Filament\Forms\Components\Textarea;
use Filament\Forms\Components\Toggle;
use Filament\Schemas\Components\Wizard;
use Filament\Schemas\Components\Wizard\Step;
use Filament\Schemas\Schema;

class ProjectForm
{
    use HasSlugFromName;

    public static function configure(Schema $schema): Schema
    {
        return $schema
            ->components([
                Wizard::make([
                    Step::make('Основная информация')
                        ->schema([
                            self::withAutoGeneratedSlug(
                                TextInput::make('title')
                                    ->label('Название')
                                    ->required()
                                    ->maxLength(255),
                                ProjectRepository::class
                            ),
                            self::asReadOnlySlug(
                                TextInput::make('slug')
                                    ->label('Слаг')
                                    ->required()
                                    ->maxLength(255)
                                    ->unique(ignoreRecord: true)
                            ),
                            Textarea::make('short_description')
                                ->label('Краткое описание')
                                ->required()
                                ->rows(3)
                                ->columnSpanFull(),
                            Textarea::make('full_description')
                                ->label('Полное описание')
                                ->rows(6)
                                ->columnSpanFull(),
                        ])
                        ->columns(2),
                    Step::make('Ссылки и публикация')
                        ->schema([
                            TextInput::make('github_url')
                                ->label('Ссылка GitHub')
                                ->url()
                                ->maxLength(255),
                            TextInput::make('preview_url')
                                ->label('Ссылка на демо')
                                ->url()
                                ->maxLength(255),
                            Toggle::make('is_published')
                                ->label('Опубликован')
                                ->inline(false),
                            TextInput::make('sort')
                                ->label('Порядок')
                                ->numeric()
                                ->default(0)
                                ->required(),
                        ])
                        ->columns(2),
                    Step::make('Технологии и задачи')
                        ->schema([
                            Select::make('technologies')
                                ->label('Технологии')
                                ->relationship('technologies', 'name')
                                ->multiple()
                                ->preload()
                                ->searchable()
                                ->columnSpanFull(),
                            Repeater::make('features')
                                ->label('Что было сделано')
                                ->relationship('features')
                                ->orderColumn('sort')
                                ->schema([
                                    TextInput::make('title')
                                        ->label('Что сделано')
                                        ->required()
                                        ->maxLength(255),
                                    TextInput::make('sort')
                                        ->label('Порядок')
                                        ->numeric()
                                        ->default(0)
                                        ->required(),
                                ])
                                ->columns(2)
                                ->defaultItems(0)
                                ->reorderableWithButtons()
                                ->collapsible()
                                ->columnSpanFull(),
                        ]),
                    Step::make('Медиа')
                        ->schema([
                            SpatieMediaLibraryFileUpload::make('cover')
                                ->label('Обложка')
                                ->collection('cover')
                                ->disk('media')
                                ->visibility('public')
                                ->image()
                                ->required(),
                            SpatieMediaLibraryFileUpload::make('gallery')
                                ->label('Галерея')
                                ->collection('gallery')
                                ->disk('media')
                                ->visibility('public')
                                ->image()
                                ->multiple()
                                ->reorderable(),
                        ])
                        ->columns(2),
                ])
                    ->startOnStep(1)
                    ->columnSpanFull(),
            ]);
    }
}
